### ISSUE TITLE
The demo custom_metrics can not working properly.

### ISSUE THREAD

**Issue by knightflower1989** [topfreegames/pitaya#273]
what:

when run the custom_metrics, I find it does not listen the port 9090 as expected.
so you can't fetch metrics data use curl like:

```bash

curl localhost:9090/metrics | grep 'my_'

```

why:

the config file config.yaml mismatch the BuilderConfig struct.

how to fix:

modify config.yaml like this can make it right.

```yaml

pitaya:
  metrics:
    #prometheus:
    #  enabled: true
    custom:
      counters:
      - subsystem: room
        name: my_counter
        help: a counter example
        labels: ['tag1', 'tag2']
      gauges:
      - subsystem: room
        name: my_gauge_1
        help: a gauge example
        labels: ['tag1']
      - subsystem: room
        name: my_gauge_2
        help: a gauge example
        labels: ['tag2']
      summaries:
      - subsystem: room
        name: my_summary
        help: a summary example
        objectives: {0.7: 0.05, 0.9: 0.01, 0.99: 0.001}
        labels: ['tag1']
metrics:
  prometheus:
    enabled: true

```
